# Generated by Django 5.0.1 on 2024-02-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(blank=True),
        ),
    ]
